import {StyleSheet} from 'react-native';
import { COLORS, Fonts } from '../../utils';
import { hp, normalize, wp } from '../../components/responsive';

export const portraitStyles = StyleSheet.create({
  safeAreaStyle: {
    flex: 1,
    height: '100%',
    width: '100%',
    backgroundColor: COLORS.backColor,
  },
  titleText: {
    fontSize: normalize(16),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.white,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.backColor,
    padding: wp(4),
  },
  greeting: {
    fontSize: normalize(20),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.secondary,
  },
  subText: {
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    fontSize: normalize(14),
    marginBottom: hp(2),
  },
  stepCard: {
    backgroundColor: COLORS.primary,
    padding: wp(4),
    borderRadius: 10,
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(1),
  },
  stepTitle: {
    fontSize: normalize(16),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  stepBadge: {
    fontSize: normalize(14),
    color: COLORS.secondary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  stepCount: {
    fontSize: normalize(32),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginBottom: hp(0.5),
  },
  stepGoalText: {
    fontSize: normalize(13),
    color: 'rgba(255,255,255,0.72)',
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: hp(1.5),
  },
  stepProgressBar: {
    height: hp(1),
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: hp(1),
    overflow: 'hidden',
  },
  stepProgressFill: {
    height: '100%',
    backgroundColor: COLORS.secondary,
  },
  card: {
    backgroundColor: COLORS.primary,
    padding: wp(4),
    borderRadius: 10,
    marginBottom: hp(1.75),
  },
  bigText: {
    fontSize: normalize(18),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    marginBottom: 10,
  },
  button: {
    marginTop: hp(1),
    backgroundColor: COLORS.subPrimary,
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(3),
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    fontSize: normalize(16),
  },
  tipCard: {
    backgroundColor: COLORS.primary,
    padding: wp(3),
    borderRadius: 10,
  },
  tipText: {
    fontSize: normalize(12),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  foodStyle: {
    fontSize: normalize(16),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: 4,
  },
  dishMainView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  dishImage: {
    width: '100%',
    height: hp(23),
    borderRadius: 10,
  },
  cardTitle: {
    fontSize: normalize(18),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: hp(2),
  },
  dishCard: {
    width: '47%',
    marginBottom: hp(2),
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-around",
    // padding: 10,
    // backgroundColor: COLORS.primary,
    marginBottom: hp(2),
    
  },
  dayBox: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    padding: hp(1.2),
    borderRadius: 10,
  },
  date: {
    marginBottom: hp(1),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    fontSize: normalize(15),
    color: COLORS.white,
  },
  dateFont: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    fontSize: normalize(17),
  },
  dayFont: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    fontSize: normalize(13),
  },
  foodText: {
    fontFamily: Fonts.FONTS.PoppinsRegular,
    fontSize: normalize(16),
    color: COLORS.white,
  },
  progremView: {
    width: '100%',
    paddingVertical: hp(1),
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    marginVertical: hp(2),
    paddingHorizontal: wp(3),
  },
  programText: {
    fontSize: normalize(16),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  optionImageStyle: {
    width: wp(5),
    height: hp(5),
    resizeMode: 'contain',
  },
  calories: {
    fontSize: normalize(16),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.white,
  },
  sectionTitle: {
    fontSize: normalize(20),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.secondary,
    marginBottom: hp(1),
  },
  exerciseText: {
    fontSize: normalize(16),
    fontFamily: Fonts.FONTS.PoppinsRegular,
    color: COLORS.white,
  },
  workoutButton: {
    width: '100%',
    backgroundColor: COLORS.subPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1),
    borderRadius: 10,
    marginTop: hp(2),
  },
  startText: {
    fontSize: normalize(18),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: '#fff',
  },
  supplementCard: {
    borderRadius: 10,
    padding: wp(4),
    marginBottom: hp(1),
  },
  supplementTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp(1),
  },
  supplementName: {
    color: COLORS.white,
    fontSize: normalize(17),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  supplementTiming: {
    color: COLORS.white,
    marginTop: hp(0.5),
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  dosageBox: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingVertical: hp(0.75),
    paddingHorizontal: wp(3),
    borderRadius: 10,
  },
  dosageText: {
    color: COLORS.white,
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
})

export const landscapeStyles = StyleSheet.create({
  safeAreaStyle: {
    flex: 1,
    height: '100%',
    width: '100%',
    backgroundColor: COLORS.backColor,
  },
  titleText: {
    fontSize: normalize(16),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.white,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.backColor,
    padding: wp(4),
  },
  greeting: {
    fontSize: normalize(20),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.secondary,
  },
  subText: {
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    fontSize: normalize(14),
    marginBottom: hp(2),
  },
  stepCard: {
    backgroundColor: 'rgba(121, 180, 51, 0.15)',
    padding: wp(4),
    borderRadius: 10,
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: 'rgba(121, 180, 51, 0.28)',
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(1),
  },
  stepTitle: {
    fontSize: normalize(16),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  stepBadge: {
    fontSize: normalize(14),
    color: COLORS.secondary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
  stepCount: {
    fontSize: normalize(32),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginBottom: hp(0.5),
  },
  stepGoalText: {
    fontSize: normalize(13),
    color: 'rgba(255,255,255,0.72)',
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: hp(1.5),
  },
  stepProgressBar: {
    height: hp(1),
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: hp(1),
    overflow: 'hidden',
  },
  stepProgressFill: {
    height: '100%',
    backgroundColor: COLORS.secondary,
  },
  card: {
    backgroundColor: COLORS.primary,
    padding: wp(4),
    borderRadius: 10,
    marginBottom: hp(1.75),
  },
  bigText: {
    fontSize: normalize(18),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    marginBottom: 10,
  },
  button: {
    marginTop: hp(1),
    backgroundColor: COLORS.subPrimary,
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(3),
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    fontSize: normalize(16),
  },
  tipCard: {
    backgroundColor: COLORS.primary,
    padding: wp(3),
    borderRadius: 10,
  },
  tipText: {
    fontSize: normalize(12),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  foodStyle: {
    fontSize: normalize(16),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: 4,
  },
  dishMainView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  dishImage: {
    width: '100%',
    height: hp(23),
    borderRadius: 10,
  },
  cardTitle: {
    fontSize: normalize(18),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: hp(2),
  },
  dishCard: {
    width: '47%',
    marginBottom: hp(2),
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-around",
    // padding: 10,
    // backgroundColor: COLORS.primary,
    marginBottom: hp(2),
    
  },
  dayBox: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    padding: hp(1.2),
    borderRadius: 5,
  },
  date: {
    marginBottom: hp(1),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    fontSize: normalize(15),
    color: COLORS.white,
  },
  dateFont: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    fontSize: normalize(17),
  },
  dayFont: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    fontSize: normalize(13),
  },
  foodText: {
    fontFamily: Fonts.FONTS.PoppinsRegular,
    fontSize: normalize(15),
    color: COLORS.white,
  },
  progremView: {
    width: '100%',
    paddingVertical: hp(2),
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    marginVertical: hp(2),
    paddingHorizontal: wp(3),
  }
})