import {StyleSheet} from 'react-native';
import { hp, wp, normalize } from '../../components/responsive';
import { COLORS, Fonts } from '../../utils/index';

export const portraitStyles = StyleSheet.create({
  safeAreaStyle: {
    flex: 1,
    height: '100%',
    width: '100%',
  },
  container: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  textStyle: {
    fontSize: hp(2.8),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsBold,
  },
  mainView: {
    width: '90%',
  },
  emailPlaceHolder: {
    fontSize: hp(2.1),
    color: COLORS.textColor,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginTop: hp(2.5),
  },
  textInputView: {
    width: '100%',
    borderWidth: 0.3,
    borderColor: COLORS.black,
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    marginTop: hp(1),
    backgroundColor: COLORS.primary,
  },
  textInput: {
    marginHorizontal: wp(3),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.greyColor,
    fontSize: hp(2),
  },
  forgotPassword: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
    fontSize: hp(2),
    textAlign: 'right',
    marginTop: hp(1),
  },
  buttonView: {
    width: '100%',
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(4),
    backgroundColor: COLORS.subPrimary,
  },
  signinText: {
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
    fontSize: hp(2.2),
  },
  signupView: {
    width: '100%',
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(1),
    backgroundColor: COLORS.white,
    borderWidth: 0.4,
    borderColor: COLORS.greyColor,
  },
  signupText: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.black,
    fontSize: hp(2.2),
  },
  haveAnAccount: {
    fontSize: hp(2.1),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: hp(3),
    textAlign: 'center',
  },
  signUpText: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.primary,
    fontSize: hp(2),
    textAlign: 'center',
  },
  eyeIcon: {
    width: wp(5),
    height: hp(4),
    resizeMode: 'contain',
  },
  logoImage: {
    width: wp(60),
    height: hp(26),
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  forgotView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: {
    fontSize: hp(1.8),
    color: COLORS.errorColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: hp(1),
    marginLeft: wp(1),
  },
  headerView: {
    width: '92%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginTop: hp(9),
    marginBottom: hp(10),
  },
  homeText: {
    fontSize: hp(2),
    color: COLORS.primary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
});

export const landscapeStyles = StyleSheet.create({
  safeAreaStyle: {
    flex: 1,
    height: '100%',
    width: '100%',
  },
  container: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  textStyle: {
    fontSize: hp(2.8),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsBold,
  },
  mainView: {
    width: '50%',
  },
  emailPlaceHolder: {
    fontSize: hp(2.1),
    color: COLORS.textColor,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginTop: hp(2.5),
  },
  textInputView: {
    width: '100%',
    borderWidth: 0.3,
    borderColor: COLORS.black,
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    marginTop: hp(1),
  },
  textInput: {
    paddingHorizontal: wp(1),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.black,
    fontSize: hp(2),
  },
  forgotPassword: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.primary,
    fontSize: hp(2),
    textAlign: 'right',
    marginTop: hp(1),
  },
  buttonView: {
    width: '100%',
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(4),
    backgroundColor: COLORS.primary,
  },
  signinText: {
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
    fontSize: wp(1.7),
  },
  signupView: {
    width: '100%',
    borderRadius: 6,
    height: hp(6),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(2),
    backgroundColor: COLORS.white,
    borderWidth: 0.4,
    borderColor: COLORS.greyColor,
  },
  signupText: {
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.black,
    fontSize: wp(1.7),
  },
  haveAnAccount: {
    fontSize: hp(2.1),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: hp(3),
    textAlign: 'center',
  },
  signUpText: {
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.primary,
    fontSize: hp(2),
    textAlign: 'center',
  },
  eyeIcon: {
    width: wp(5),
    height: hp(3),
    resizeMode: 'contain',
  },
  logoImage: {
    width: wp(40),
    height: hp(20),
    resizeMode: 'contain',
  },
  forgotView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: {
    fontSize: hp(1.8),
    color: COLORS.errorColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: hp(1),
    marginLeft: wp(1),
  },
  headerView: {
    width: '92%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginTop: hp(9),
    marginBottom: hp(10),
  },
  homeText: {
    fontSize: hp(2),
    color: COLORS.primary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
  },
});