# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
    __dir__
  ]
).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

# React Native Firebase
$RNFirebaseDisableSPM = true

# Firebase requires frameworks for the Swift pods
use_frameworks! :linkage => :static

target 'AiHealthCare' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Required module maps for Firebase Swift dependencies
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Firebase Swift module/header configuration
    firebase_targets = [
      'FirebaseAuth',
      'FirebaseCore',
      'FirebaseCoreInternal',
      'FirebaseCoreExtension',
      'FirebaseAuthInterop',
      'FirebaseAppCheckInterop',
      'FirebaseMessagingInterop',
      'GoogleUtilities',
      'RecaptchaInterop'
    ]

    installer.pods_project.targets.each do |target|
      if firebase_targets.include?(target.name)

        target.build_configurations.each do |build_config|

          build_config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          build_config.build_settings['DEFINES_MODULE'] = 'YES'

        end

      end
    end
  end
end
