import {StyleSheet} from 'react-native';
import { COLORS, Fonts } from '../../utils';
import { hp, normalize, wp } from '../../components/responsive';

export const portraitStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backColor,
  },
  headerView: {
    height: '8%',
    width: '100%',
    backgroundColor: COLORS.primary,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 5,
    paddingBottom: 15,
  },
  title: {
    fontSize: normalize(23),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.secondary,
  },
  subtitle: {
    fontSize: normalize(14),
    color: COLORS.white,
    marginTop: 5,
    fontFamily: Fonts.FONTS.PoppinsRegular,
  },
  searchContainer: {
    height: 42,
    marginHorizontal: 20,
    marginBottom: 15,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E5E9EF',
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: normalize(14),
    color: COLORS.white,
    paddingVertical: 0,
  },
  filterHeader: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  filterTitle: {
    fontSize: normalize(17),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
  },
  clearText: {
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.secondary,
  },
  filters: {
    paddingHorizontal: 20,
    gap: 8,
  },
  dropdown: {
    height: 45,
    borderWidth: 1,
    borderColor: '#E1E6ED',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
  },
  dropdownContainer: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E1E6ED',
  },
  placeholder: {
    fontSize: 13,
    color: '#7A8491',
  },
  selectedText: {
    fontSize: 13,
    color: '#17202A',
    fontWeight: '500',
  },
  itemText: {
    fontSize: 13,
    color: '#17202A',
  },
  resultHeader: {
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  resultText: {
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.greyColor,
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  card: {
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
  },
  cardTop: {
    flexDirection: 'row',
  },
  profileImage: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#E9EEF3',
  },
  doctorInfo: {
    flex: 1,
    marginLeft: 12,
  },
  doctorName: {
    fontSize: normalize(17),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
  },
  specialist: {
    fontSize: normalize(15),
    color: COLORS.secondary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginTop: 3,
  },
  degree: {
    fontSize: normalize(13),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: 4,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  star: {
    fontSize: normalize(14),
    color: '#F5A623',
  },
  rating: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.white,
    marginLeft: 4,
  },
  reviews: {
    fontSize: normalize(13),
    color: COLORS.greyColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginLeft: 4,
  },
  divider: {
    height: 1,
    backgroundColor: '#EEF1F4',
    marginVertical: 14,
  },
  experienceRow: {
    flexDirection: 'row',
  },
  infoBox: {
    flex: 1,
  },
  infoLabel: {
    fontSize: normalize(12),
    color: COLORS.greyColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: 3,
  },
  infoValue: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
  },
  fee: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.secondary,
  },
  featuresContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 6,
  },
  feature: {
    backgroundColor: '#F0F7F3',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 6,
  },
  featureText: {
    fontSize: normalize(12),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  availabilityContainer: {
    flexDirection: 'row',
    marginTop: 14,
  },
  timeContainer: {
    marginLeft: 30,
  },
  availableText: {
    fontSize: normalize(13),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  consultButton: {
    paddingVertical: hp(1.2),
    borderRadius: 10,
    backgroundColor: COLORS.subPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
  },
  consultButtonText: {
    color: COLORS.white,
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsBold,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 30,
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 15,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#17202A',
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 13,
    color: '#7A8491',
    marginTop: 7,
  },
  emptyButton: {
    marginTop: 20,
    backgroundColor: '#2E8B57',
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 8,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
  },
  dropdown2DropdownStyle: {
    backgroundColor: COLORS.white,
    borderRadius: 4,
    paddingVertical: hp(1),
    // height: hp(25),
    // borderRadius: 12,
  },
  dropdownItemTxtStyle: {
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    fontSize: hp(2.1),
    paddingLeft: wp(2),
  },
  dropdownView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp(1),
    // height: hp(4),
    borderBottomWidth: 0,
  },
  dropdown2BtnStyle2: {
    width: '100%',
    paddingVertical: hp(0.5),
    backgroundColor: COLORS.white,
    borderRadius: 5,
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: COLORS.primary,
    // marginTop: hp(1),
    justifyContent: 'space-between',
  },
  filterImage: {
    width: wp(4),
    height: hp(2.5),
    resizeMode: 'contain',
    tintColor: COLORS.greyColor,
  },
});

export const landscapeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.backColor,
  },
  headerView: {
    height: '8%',
    width: '100%',
    backgroundColor: COLORS.primary,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 5,
    paddingBottom: 15,
  },
  title: {
    fontSize: normalize(23),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.secondary,
  },
  subtitle: {
    fontSize: normalize(14),
    color: COLORS.white,
    marginTop: 5,
    fontFamily: Fonts.FONTS.PoppinsRegular,
  },
  searchContainer: {
    height: 42,
    marginHorizontal: 20,
    marginBottom: 15,
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E5E9EF',
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: normalize(14),
    color: COLORS.white,
    paddingVertical: 0,
  },
  filterHeader: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  filterTitle: {
    fontSize: normalize(17),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
  },
  clearText: {
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.secondary,
  },
  filters: {
    paddingHorizontal: 20,
    gap: 8,
  },
  dropdown: {
    height: 45,
    borderWidth: 1,
    borderColor: '#E1E6ED',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
  },
  dropdownContainer: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E1E6ED',
  },
  placeholder: {
    fontSize: 13,
    color: '#7A8491',
  },
  selectedText: {
    fontSize: 13,
    color: '#17202A',
    fontWeight: '500',
  },
  itemText: {
    fontSize: 13,
    color: '#17202A',
  },
  resultHeader: {
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  resultText: {
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.greyColor,
  },
  listContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  card: {
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
  },
  cardTop: {
    flexDirection: 'row',
  },
  profileImage: {
    width: 75,
    height: 75,
    borderRadius: 12,
    backgroundColor: '#E9EEF3',
  },
  doctorInfo: {
    flex: 1,
    marginLeft: 12,
  },
  doctorName: {
    fontSize: normalize(17),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
  },
  specialist: {
    fontSize: normalize(15),
    color: COLORS.secondary,
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    marginTop: 3,
  },
  degree: {
    fontSize: normalize(13),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginTop: 4,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  star: {
    fontSize: normalize(14),
    color: '#F5A623',
  },
  rating: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.white,
    marginLeft: 4,
  },
  reviews: {
    fontSize: normalize(13),
    color: COLORS.greyColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginLeft: 4,
  },
  divider: {
    height: 1,
    backgroundColor: '#EEF1F4',
    marginVertical: 14,
  },
  experienceRow: {
    flexDirection: 'row',
  },
  infoBox: {
    flex: 1,
  },
  infoLabel: {
    fontSize: normalize(12),
    color: COLORS.greyColor,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    marginBottom: 3,
  },
  infoValue: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.white,
  },
  fee: {
    fontSize: normalize(14),
    fontFamily: Fonts.FONTS.PoppinsSemiBold,
    color: COLORS.secondary,
  },
  featuresContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
    gap: 6,
  },
  feature: {
    backgroundColor: '#F0F7F3',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 6,
  },
  featureText: {
    fontSize: normalize(12),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  availabilityContainer: {
    flexDirection: 'row',
    marginTop: 14,
  },
  timeContainer: {
    marginLeft: 30,
  },
  availableText: {
    fontSize: normalize(13),
    color: COLORS.white,
    fontFamily: Fonts.FONTS.PoppinsMedium,
  },
  consultButton: {
    paddingVertical: hp(1.2),
    borderRadius: 10,
    backgroundColor: COLORS.subPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
  },
  consultButtonText: {
    color: COLORS.white,
    fontSize: normalize(15),
    fontFamily: Fonts.FONTS.PoppinsBold,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 30,
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 15,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#17202A',
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 13,
    color: '#7A8491',
    marginTop: 7,
  },
  emptyButton: {
    marginTop: 20,
    backgroundColor: '#2E8B57',
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 8,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
  },
  dropdown2DropdownStyle: {
    backgroundColor: COLORS.white,
    borderRadius: 4,
    paddingVertical: hp(1),
    // height: hp(25),
    // borderRadius: 12,
  },
  dropdownItemTxtStyle: {
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsMedium,
    fontSize: hp(2.1),
    paddingLeft: wp(2),
  },
  dropdownView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp(1),
    // height: hp(4),
    borderBottomWidth: 0,
  },
  dropdown2BtnStyle2: {
    width: '100%',
    paddingVertical: hp(0.5),
    backgroundColor: COLORS.white,
    borderRadius: 5,
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: COLORS.primary,
    // marginTop: hp(1),
    justifyContent: 'space-between',
  },
  filterImage: {
    width: wp(4),
    height: hp(2.5),
    resizeMode: 'contain',
    tintColor: COLORS.greyColor,
  },
});